services:
  nginx:
    image: nginx:1.27-alpine
    container_name: nginx
    ports:
      - "80:80"
    environment:
      - TZ=Asia/Bangkok
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./public:/usr/share/nginx/html/public
    depends_on:
      - nextjs

  nextjs:
    image: node:23-alpine
    container_name: nextjs
    ports:
      - "3000:3000"
    volumes:
      - .next/standalone:/nextjs
    working_dir: /nextjs
    command: sh -c "node server.js"